[package]
name = "aion"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = [
    ".",
    "aion-ecs",
    "aion-event",
    "aion-event-systems/aion-event-clock",
    "aion-event-systems/aion-event-conditional",
    "aion-event-systems/aion-event-executable",
    "aion-event-systems/aion-event-mapper",
    "aion-event-systems/aion-event-processor",
    "aion-processor",
    "aion-program",
    "aion-reactor",
    "aion-state",
    "aion-system",
    "execution_graph",
]

[workspace.dependencies]
aion-state = { path = "aion-state", features = ["sync", "releaser", "notifier", "async"] }

rand = "0.10.3"
rand_chacha = "0.10.0"

serde = { version = "1.0.229", features = ["derive"] }

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_unused = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"